# This is a basic workflow to help you get started with Actions
name: Create EKS and deploy add-ons

on: 
  push:
    branches:
      - main
      
jobs:
  terraform-create-cluster: 
    name: "create-cluster"
    runs-on: self-hosted
    steps:
      - name: Git clone the repository # Clone the repo
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
          
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform # Use your environment folder
        shell: bash
        
      # - name: Terraform Apply
      #   id: apply
      #   run: |
      #     terraform apply --auto-approve 
      #   working-directory: ./terraform # Use your environment folder
      #   shell: bash
        
      - name: Terraform Destroy
        id: destroy
        run: |
          terraform destroy --auto-approve 
        working-directory: ./terraform # Use your environment folder
        shell: bash



